alias démarrer='sudo systemctl start instakilo && echo -e "\n\n\e[32mLe serveur a bien démarré !!!\e[0m\n"'
alias arrêter='sudo systemctl stop instakilo && echo -e "\n\n\e[31mLe serveur est bien à l arrêt...\e[0m\n"'
