---

- name: Upgrade all packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400
    upgrade: yes

- name: Install some packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400
    state: latest
    pkg:
    - vim
    - tree
    - sl

- name: Create .ssh directory if it does not exist
  ansible.builtin.file:
    path: /home/rpi/.ssh
    state: directory
    owner: rpi
    group: www-data
    mode: '0755'

- name: Import bash aliases definition
  ansible.builtin.copy:
    src: bash_aliases
    dest: /home/rpi/.bash_aliases
    owner: rpi
    group: rpi
    mode: "0644"

- name: Import systemd service definition for instakilo
  ansible.builtin.copy:
    src: instakilo.service
    dest: /lib/systemd/system/instakilo.service
    owner: root
    group: root
    mode: "0644"

